---
title: "DS_assignment4_19163147"
author: "Jaspreet Gill (19163147)"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    toc: yes
---
# Exercise 1
```{r include=FALSE}
library(tidyverse)
library(phyloseq)
metadata = read.table(file="Saanich.metadata.txt", header=TRUE, row.names=1, sep="\t")
load("phyloseq_object.RData")
physeq_percent = transform_sample_counts(physeq, function(x) 100 * x/sum(x))
```

```{r echo=TRUE, message=FALSE, warning=FALSE}
#Specify geom to add data, customized as purple triangles
ggplot(metadata, aes(x=PO4_uM, y=Depth_m)) +
  geom_point(color="purple", shape=17)
```

# Exercise 2
```{r echo=TRUE, message=FALSE, warning=FALSE}
#Convert temperature column from Celcius to Fahrenheit using mutate function
#Plot temperature in F vs depth

metadata %>%
  mutate(Temperature_F = 1.8*Temperature_C + 32) %>%
  ggplot() + geom_point(aes(x=Temperature_F, y=Depth_m))
```

# Exercise 3
```{r echo=TRUE, fig.height=15, fig.width=30, message=FALSE, warning=FALSE}
#Plotting class level communities by depth by specifying the fill
#Getting rid of black lines with specifying stat as "Identity"
#Add title and axis labels with ggtitle, xlab, and ylab
plot_bar(physeq_percent, fill="Class") + 
  geom_bar(aes(fill=Class), stat="identity") +  
  ggtitle("Classes from 10-200m in Saanich Inlet") +
  xlab("Sample depth") + ylab("Percent relative abundance")
```

#Exercise 4
```{r echo=TRUE, message=FALSE, warning=FALSE}
#Gather(new variable, variable values, column names)
#Geom_line to connect data points
#Use facet_wrap function to separate data into different graohs
#Let R scale y-axis idependently for each panel 
metadata %>% 
  gather(Nutrients_uM, uM, NH4_uM, NO2_uM, NO3_uM, O2_uM, PO4_uM, SiO2_uM) %>%
  ggplot() +geom_point(aes(x=Depth_m, y=uM)) + geom_line(aes(x=Depth_m, y=uM)) +
  facet_wrap(~Nutrients_uM, scales="free_y") 

```
