---
title: "Project 2 self-assessment of contributions"
author: Jaspreet Gill (19163147)
subtitle: "2018 Term 2 - MICB425"
output: html_document
---

## Abstract  
I wrote the first part (introduction and methods) of the abstract.

### Writing
I wrote the introduction and methods.  

### Editing
I helped with editing the paper.  


## Introduction
### Literature research
I did the literature research.  

### Writing
I wrote the introduction.  

### Editing
I edited the introduction.  


## Methods
### Writing
I wrote the methods section except for the part about R.

### Editing
I edited the methods.  


## Results
### Analysis 
I wrote the script, did the TreeSAPP analysis and troubleshooting, iTOL plots, and gathering of data.  

### Figures
I helped with ideas for the figures.  

### Writing
I did not write the results.  

### Editing
I edited the results.  


## Discussion
### Literature research
I did not do the literature research for the discussion.  

### Writing
I did not write the discussion.  

### Editing
I edited the discussion.  


